---
# Setup K8 master
# wget https://docs.projectcalico.org/manifests/calico.yaml
#
#- name: create k8 cluster specifying pod network matching calico.yaml
#  become: yes
#  shell: 
#        'kubeadm init --pod-network-cidr=10.0.0.0/16  --apiserver-advertise-address=10.0.0.20'

- name: Create .kube directory
  file:
          path: /home/vagrant/.kube
          state: directory

- name: Copy k8 config file
  become: yes
  copy:
          remote_src: yes
          src: /etc/kubernetes/admin.conf
          dest: /home/vagrant/.kube/config
          owner: vagrant
          group: vagrant

- name: Setup pod network
  become: no
  shell:
        'kubectl apply -f /home/vagrant/calico.yaml'
