---
# Inital OS setup for k8 nodes
- name: update OS to lastest version, installing extra packages
  hosts: k8all
  become: yes
  roles:
          - initial-setup

- name: setting up ssh key
  hosts: k8all
  tasks:
          - name: using simple shell command
            shell:
                    'ssh-keygen -t rsa -b 2048  -f /home/vagrant/.ssh/id_rsa -q -P ""'


