---
# Install K8 on master and nodes

- name: Install docker
  apt:
        name: docker.io
        state: present

- name: Start Docker persistently
  service:
        name: docker
        state: started
        enabled: yes
              
- name: Install helper packages
  apt:
        name: 
                - apt-transport-https
                - curl
        state: present

- name: add key for K8
  apt_key:
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          state: present

- name: add K8 repository
  apt_repository:
          repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
          state: present

- name: install K8 packages
  apt:
          name:
                  - kubeadm 
                  - kubelet
                  - kubectl
                  - kubernetes-cni
          state: present

- name: Remove swapfile from /etc/fstab
  mount:
          name: "{{ item }}"
          fstype: swap
          state: absent
  with_items:
          - swap
          - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0   
