---
# OS upgrade, additional packages, /etc/hosts

- name: OS upgrade
  apt:
          upgrade: dist
          update_cache: yes

- name: additional packages
  apt:
          name:
                  - tree
                  - sshpass
                  - net-tools

- name: Copy /etc/hosts file
  copy:
          src: hosts
          dest: /etc/hosts
